# Site settings
title: oh my blog
email: wendi@createsalesandmarketing.com
description: > # this means to ignore newlines until "baseurl:"
  OH MY BLOG | Rants, Raves & Musings by that chick Wendi Donaldson-Speciale
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook: http://www.facebook.com/wendidonaldsonspeciale
twitter_username: WendiSpeciale
github_username:  AreYouCereal

# Build settings
markdown: kramdown
