# Site settings
title: oh my blog
email: wendi@createsalesandmarketing.com
description: > # this means to ignore newlines until "baseurl:"
  Just a mom working full time while attending makersqure in Austin, Texas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: WendiSpeciale
github_username:  AreYouCereal

# Build settings
markdown: kramdown
